routes:
  - match:
      # prefix: 匹配以 "/pyapi" 为前缀的请求路径
      prefix: "/pyapi"
    # route: 定义匹配成功后的路由行为
    route:
      # cluster: 将请求路由到名为 "py_api_svc_cluster" 的集群
      cluster: py_api_svc_cluster
      # prefix_rewrite: 在转发到上游之前，将请求路径的前缀重写为 "/"
      prefix_rewrite: "/"
      # host_rewrite_literal: 将请求的 Host 头重写为指定的字面值
      host_rewrite_literal: py-api-svc-912156613264.europe-west2.run.app
  # - match: 定义第二个路由规则的匹配条件

clusters:
  - name: py_api_svc_cluster
    # connect_timeout: 与上游主机建立连接的超时时间
    connect_timeout: 5s
    # type: 服务发现类型，LOGICAL_DNS 表示 Envoy 会定期解析 DNS 以获取端点
    type: LOGICAL_DNS
    # dns_lookup_family: DNS 解析时只使用 IPv4
    dns_lookup_family: V4_ONLY
    # lb_policy: 负载均衡策略，ROUND_ROBIN 表示轮询
    lb_policy: ROUND_ROBIN
    # load_assignment: 静态地定义集群的端点
    load_assignment:
      # cluster_name: 关联的集群名称
      cluster_name: py_api_svc_cluster
      # endpoints: 端点列表
      endpoints:
      # - lb_endpoints: 负载均衡端点列表
      - lb_endpoints:
        # - endpoint: 单个端点
        - endpoint:
            # address: 端点地址
            address:
              # socket_address: 使用套接字地址进行配置
              socket_address:
                # address: 上游服务的主机名
                address: py-api-svc-912156613264.europe-west2.run.app
                # port_value: 上游服务的端口号，这里是 443 (HTTPS)
                port_value: 443
    # metadata: 为集群添加元数据，可被其他过滤器使用
    metadata:
      # typed_filter_metadata: 为特定过滤器提供类型化的元数据
      typed_filter_metadata:
        # envoy.filters.http.gcp_authn: 为 GCP 认证过滤器提供元数据
        envoy.filters.http.gcp_authn:
          # "@type": 指定元数据类型为 Audience
          "@type": type.googleapis.com/envoy.extensions.filters.http.gcp_authn.v3.Audience
          # url: 指定用于生成 JWT 的目标受众（audience）
          url: https://py-api-svc-912156613264.europe-west2.run.app
    # transport_socket: 配置与上游主机通信时使用的传输套接字，例如 TLS
    transport_socket:
      # name: 指定使用 TLS 传输套接字
      name: envoy.transport_sockets.tls
      # typed_config: 提供 TLS 的详细配置
      typed_config:
        # "@type": 指定配置类型为上游 TLS 上下文
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
  # - name: 定义第二个集群的名称，用于 UI 服务
